### ISSUE TITLE
Naming format

### ISSUE THREAD

**Issue by Torwent** [Villavu/Simba-Build-Archive-Old#1]
Just a small suggestion.
As someone that works daily with thousands of files and seeing this as a long term build archive, the naming pattern should probably be `YYYY-MM-DD` so the builds are not mixed everywhere. It's not too bad rn now but it will be as we approach 100+ builds.

**Comment by Torwent** [comment]
Also, including the hour/mins might also be useful but not too important anyway

**Comment by slackydev** [comment]
I like DD-MM-YYYY it's what we use in Norway :-p

**Comment by Torwent** [comment]
it's what we use in all europe I think lol but for file organization YYYY-MM-DD is better, you will see when we have over 100 builds here if github even allows it lol

**Comment by slackydev** [comment]
I get it, makes sense.

**Comment by ollydev** [comment]
It's better now in https://github.com/Villavu/Simba-Build-Archive
I will delete this repo eventually.
